// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpAn.App.MorphTrade.Domain.Flows;

#nullable disable

namespace OpAn.App.MorphTrade.Domain.Flows.Migrations
{
    [DbContext(typeof(FlowsDbContext))]
    [Migration("20260105175810_TradeCallInfoAdded")]
    partial class TradeCallInfoAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpAn.App.MorphTrade.Domain.Flows.Entities.CallResponseEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBacktesting")
                        .HasColumnType("boolean");

                    b.Property<string>("TradeCall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "Timestamp");

                    b.HasIndex("FlowId");

                    b.ToTable("CallResponseEvents");
                });

            modelBuilder.Entity("OpAn.App.MorphTrade.Domain.Flows.Entities.FlowMeta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("OpAn.App.MorphTrade.Domain.Flows.Entities.CallResponseEvent", b =>
                {
                    b.HasOne("OpAn.App.MorphTrade.Domain.Flows.Entities.FlowMeta", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OpAn.App.MorphTrade.Abstractions.Finance.Ticker", "Ticker", b1 =>
                        {
                            b1.Property<string>("CallResponseEventId")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CallResponseEventTimestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric");

                            b1.Property<long>("Quantity")
                                .HasColumnType("bigint");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("Volume")
                                .HasColumnType("numeric");

                            b1.HasKey("CallResponseEventId", "CallResponseEventTimestamp");

                            b1.ToTable("CallResponseEvents");

                            b1.WithOwner()
                                .HasForeignKey("CallResponseEventId", "CallResponseEventTimestamp");
                        });

                    b.OwnsOne("OpAn.App.MorphTrade.Domain.Flows.Entities.TradeCallInfoEvent", "TradeCallInfo", b1 =>
                        {
                            b1.Property<string>("CallResponseEventId")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CallResponseEventTimestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("Entry")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("StopLoss")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("TakeProfit")
                                .HasColumnType("numeric");

                            b1.Property<int>("TradeCall")
                                .HasColumnType("integer");

                            b1.HasKey("CallResponseEventId", "CallResponseEventTimestamp");

                            b1.ToTable("CallResponseEvents");

                            b1.WithOwner()
                                .HasForeignKey("CallResponseEventId", "CallResponseEventTimestamp");
                        });

                    b.Navigation("Flow");

                    b.Navigation("Ticker")
                        .IsRequired();

                    b.Navigation("TradeCallInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
