<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MorphTrade.Domain.Finance.Bank\MorphTrade.Domain.Finance.Bank.csproj" />
      <ProjectReference Include="..\MorphTrade.Domain.Finance\MorphTrade.Domain.Finance.csproj" />
    </ItemGroup>

</Project>
